import type { NextPage } from "next";
import Head from "next/head";
import { Box, Text } from "@localyze-pluto/components";
import { globalStyles } from "@localyze-pluto/theme";

const Home: NextPage = () => {
  globalStyles();
  return (
    <Box
      padding="space100"
      backgroundColor="colorBackgroundBody"
      css={{ height: "100vh" }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="header" marginBottom="space60">
        <Text as="h5" textTransform="uppercase" color="colorTextStrongest">
          Welcome back!
        </Text>
        <Text
          as="h1"
          color="colorTextStrongest"
          fontWeight="fontWeightBold"
          fontSize="fontSize50"
          lineHeight="lineHeight60"
        >
          Let&apos;s move beyond borders today
        </Text>
      </Box>
      <Box
        as="main"
        css={{
          display: "grid",
          gap: "$space60",
          "@media (min-width: 800px)": {
            gridTemplateColumns: "1fr 250px",
          },
        }}
      >
        <Box
          css={{
            display: "grid",
            gap: "$space60",
            "@media (min-width: 800px)": {
              gridTemplateColumns: "1fr 1fr",
            },
          }}
        >
          <Box
            as="a"
            href="#"
            background="colorBackgroundGradientTasks"
            borderRadius="borderRadius40"
            color="colorTextInverse"
            css={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              textDecoration: "none",
              "&:hover": {
                cursor: "pointer",
                boxShadow: "$shadowStrong",
              },
              "&:focus": {
                boxShadow: "$shadowFocus",
                outline:
                  "$borderWidths$borderWidth20 solid $colorBorderPrimary !important",
                outlineOffset: "$space$space10",
              },
              "@media (max-width: 800px)": {
                gridColumn: "1 / span 2",
              },
            }}
            fontFamily="moderat"
            padding="space150"
          >
            <Text
              fontSize="fontSize80"
              lineHeight="lineHeight90"
              fontWeight="fontWeightBold"
              color="colorTextInverse"
            >
              5
            </Text>
            <Text
              fontSize="fontSize30"
              lineHeight="lineHeight40"
              color="colorTextInverse"
            >
              My Tasks
            </Text>
          </Box>

          <Box
            as="a"
            href="#"
            background="colorBackgroundGradientProcesses"
            borderRadius="borderRadius40"
            color="colorTextInverse"
            css={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              textDecoration: "none",
              "&:hover": {
                cursor: "pointer",
                boxShadow: "$shadowStrong",
              },
              "&:focus": {
                boxShadow: "$shadowFocus",
                outline:
                  "$borderWidths$borderWidth20 solid $colorBorderPrimary !important",
                outlineOffset: "$space$space10",
              },
              "@media (max-width: 800px)": {
                gridColumn: "1 / span 2",
              },
            }}
            fontFamily="moderat"
            padding="space150"
          >
            <Text
              fontSize="fontSize80"
              lineHeight="lineHeight90"
              fontWeight="fontWeightBold"
              color="colorTextInverse"
            >
              9
            </Text>
            <Text
              fontSize="fontSize30"
              lineHeight="lineHeight40"
              color="colorTextInverse"
            >
              My Processes
            </Text>
          </Box>

          <Box
            backgroundColor="colorBackground"
            borderRadius="borderRadius40"
            padding="space80"
            css={{ gridColumn: "1 / span 2" }}
          >
            <Text
              as="h3"
              color="colorTextStrongest"
              fontWeight="fontWeightMedium"
              fontSize="fontSize40"
              lineHeight="lineHeight50"
            >
              Here&apos;s what happened recently
            </Text>
            <Box
              marginTop="space180"
              marginBottom="space180"
              css={{ textAlign: "center" }}
            >
              <Text fontSize="fontSize30" lineHeight="lineHeight40">
                There is no news yet, check back later.
              </Text>
            </Box>
          </Box>
        </Box>

        <Box css={{ display: "grid", gap: "$space60" }}>
          <Box
            backgroundColor="colorBackground"
            borderRadius="borderRadius40"
            padding="space80"
          >
            <Text
              as="h3"
              color="colorTextStrongest"
              fontWeight="fontWeightMedium"
              fontSize="fontSize30"
              lineHeight="lineHeight40"
            >
              Feel lost? Start with a Pre-check!
            </Text>
            <Box marginTop="space60">
              <Text
                color="colorTextStrongest"
                fontWeight="fontWeightBold"
                fontSize="fontSize80"
                lineHeight="lineHeight90"
              >
                0
              </Text>
              <Text
                as="h3"
                color="colorTextStrongest"
                fontWeight="fontWeightMedium"
                fontSize="fontSize30"
                lineHeight="lineHeight40"
              >
                submitted pre-checks this month
              </Text>
            </Box>
          </Box>

          <Box
            backgroundColor="colorBackground"
            borderRadius="borderRadius40"
            padding="space80"
          >
            <Text
              as="h3"
              color="colorTextStrongest"
              fontWeight="fontWeightMedium"
              fontSize="fontSize30"
              lineHeight="lineHeight40"
            >
              Localyze has supported you with
            </Text>
            <Box marginTop="space60">
              <Text
                color="colorTextStrongest"
                fontWeight="fontWeightBold"
                fontSize="fontSize80"
                lineHeight="lineHeight90"
              >
                23
              </Text>
              <Text
                color="colorTextStrongest"
                fontWeight="fontWeightMedium"
                fontSize="fontSize30"
                lineHeight="lineHeight40"
              >
                {" "}
                processes
              </Text>
            </Box>
            <Box>
              <Text
                color="colorTextStrongest"
                fontWeight="fontWeightMedium"
                fontSize="fontSize30"
                lineHeight="lineHeight40"
              >
                from
              </Text>
              <Text
                color="colorTextStrongest"
                fontWeight="fontWeightBold"
                fontSize="fontSize50"
                lineHeight="lineHeight60"
              >
                {" "}
                12{" "}
              </Text>
              <Text
                color="colorTextStrongest"
                fontWeight="fontWeightMedium"
                fontSize="fontSize30"
                lineHeight="lineHeight40"
              >
                nationalities
              </Text>
            </Box>
          </Box>
        </Box>
      </Box>
    </Box>
  );
};

export default Home;
